coverage:
  status:
    patch: off
    project:
      default:
        threshold: 1%
        target: 50%
ignore:
  - "client/swagger/http"
  - "client/swagger/models"
  - "client/swagger/operations"
  - "dashboard/model2ts"
  - "docs/gen"
  - "handler/storage/gen"
  - "handler/storage/types_gen.go"
  - "cmd/testutil.go"
