name: Setup Cache
description: Setup Cache
runs:
  using: "composite"
  steps:
    - name: Setup Golang caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ matrix.os }}-golang-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ matrix.os }}-golang-${{ matrix.go }}-
    - name: Setup PostgreSQL database
      uses: ikalnytskyi/action-setup-postgres@v4
      with:
        username: 'singularity'
        password: 'singularity'
        database: 'singularity'
    - name: Setup MySQL database
      uses: shogo82148/actions-setup-mysql@v1
      with:
        user: 'singularity'
        password: 'singularity'
    - name: Create MySQL database
      shell: bash
      run: mysql -u root -e "create database singularity"
    - name: Setup no parallel for win32 test
      if: matrix.os == 'windows'
      shell: bash
      run: |
          echo "GOMAXPROCS=1" >> $GITHUB_ENV
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '6.0'
        mongodb-port: 27018
