name: Setup Cache
description: Setup Cache
runs:
  using: "composite"
  steps:
    - name: Setup nodejs
      uses: actions/setup-node@v3
      with:
          node-version: '18'
          cache: 'npm'
    - run: npm ci
    - name: Setup Golang caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ matrix.os }}-golang-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ matrix.os }}-golang-${{ matrix.go }}-
