name: Go Generate and Commit

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.PAT }}

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.x'

    - name: Run go generate
      run: |
        go generate ./...

    - name: Commit and push if changed
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Go generate"
