# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout=10m

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2023.1.3"
          install-go: false

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod

      - name: Build
        run: make build

      - name: Test
        run: go test -coverprofile=coverage.out -coverpkg=./... ./...
        env:
          TEST_WALLET_KEY: ${{ secrets.TEST_WALLET_KEY }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Bump version and push tag
        if: github.event_name != 'pull_request'
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
