# All the other checks that are not covered by unified CI
name: golang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golang:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Setup PostgreSQL database
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: 'singularity'
          password: 'singularity'
          database: 'singularity'

      - name: Setup MySQL database
        uses: shogo82148/actions-setup-mysql@v1
        with:
          user: 'singularity'
          password: 'singularity'

      - name: Create MySQL database
        shell: bash
        run: mysql -u root -e "create database singularity"

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout=10m

      - name: Run tests (32 bit)
        uses: protocol/multiple-go-modules@v1.2
        env:
          GOARCH: 386
        with:
          run: |
            export "PATH=$PATH_386:$PATH"
            go test -v -shuffle=on ./...
